### PR TITLE
modified look & hover

### PR DESCRIPTION
**Pull request by MePriyanshuHoo**
1. modified colors 
2. changed intro text
3. **removed IIIT Bhopal** 
4. edited hover effect 
5. changed the main image
6. removed logo for home page

### CODE REVIEW

**Comment by MePriyanshuHoo** [comment]
draft kar raha hoo thoda aur edit karna he

**Comment by umgbhalla** [comment]
ss daldo idhar

**Comment by MePriyanshuHoo** [comment]
image

**Comment by tanav2202** [comment]
color theme blue and purple pe hai 
navbar se green uda de

**Comment by yadavnarun** [comment]
1. follow color scheme
2. use same units in css (eg: if using rem do not use px for font size)
3. refrain from writing redundant code (https://stackoverflow.com/questions/40603397/how-to-use-css-classes-in-best-way-without-redundant)

**Pull request closed without merging**
